/* Auto-generated by tools/migrate_drivers_to_srstd.py. Do not edit. */
#include "srstd.h"

/* extern declarations — force linker to pull in each driver's api.o */
extern struct sr_dev_driver agdmm_driver_info;
extern struct sr_dev_driver appa_55ii_driver_info;
extern struct sr_dev_driver arachnid_labs_re_load_pro_driver_info;
extern struct sr_dev_driver asix_omega_rtm_cli_driver_info;
extern struct sr_dev_driver asix_sigma_driver_info;
extern struct sr_dev_driver atorch_driver_info;
extern struct sr_dev_driver atten_pps3203_driver_info;
extern struct sr_dev_driver bkprecision_1856d_driver_info;
extern struct sr_dev_driver cem_dt_885x_driver_info;
extern struct sr_dev_driver center_309_driver_info;
extern struct sr_dev_driver voltcraft_k204_driver_info;
extern struct sr_dev_driver chronovu_la_driver_info;
extern struct sr_dev_driver colead_slm_driver_info;
extern struct sr_dev_driver conrad_digi_35_cpu_driver_info;
extern struct sr_dev_driver devantech_eth008_driver_info;
extern struct sr_dev_driver fluke_45_driver_info;
extern struct sr_dev_driver flukedmm_driver_info;
extern struct sr_dev_driver ftdi_la_driver_info;
extern struct sr_dev_driver fx2lafw_driver_info;
extern struct sr_dev_driver gmc_mh_1x_2x_rs232_driver_info;
extern struct sr_dev_driver gmc_mh_2x_bd232_driver_info;
extern struct sr_dev_driver greatfet_driver_info;
extern struct sr_dev_driver gwinstek_gds_800_driver_info;
extern struct sr_dev_driver gwinstek_gpd_driver_info;
extern struct sr_dev_driver gwinstek_psp_driver_info;
extern struct sr_dev_driver hameg_hmo_driver_info;
extern struct sr_dev_driver hantek_4032l_driver_info;
extern struct sr_dev_driver hantek_6xxx_driver_info;
extern struct sr_dev_driver hantek_dso_driver_info;
extern struct sr_dev_driver hp_3457a_driver_info;
extern struct sr_dev_driver hp_3478a_driver_info;
extern struct sr_dev_driver hp_59306a_driver_info;
extern struct sr_dev_driver icstation_usbrelay_driver_info;
extern struct sr_dev_driver ikalogic_scanalogic2_driver_info;
extern struct sr_dev_driver ikalogic_scanaplus_driver_info;
extern struct sr_dev_driver ipdbg_la_driver_info;
extern struct sr_dev_driver itech_it8500_driver_info;
extern struct sr_dev_driver juntek_jds6600_driver_info;
extern struct sr_dev_driver kecheng_kc_330b_driver_info;
extern struct sr_dev_driver kingst_la2016_driver_info;
extern struct sr_dev_driver korad_kaxxxxp_driver_info;
extern struct sr_dev_driver lascar_el_usb_driver_info;
extern struct sr_dev_driver lecroy_logicstudio_driver_info;
extern struct sr_dev_driver lecroy_xstream_driver_info;
extern struct sr_dev_driver manson_hcs_3xxx_driver_info;
extern struct sr_dev_driver mastech_ms6514_driver_info;
extern struct sr_dev_driver maynuo_m97_driver_info;
extern struct sr_dev_driver mic_98581_driver_info;
extern struct sr_dev_driver mic_98583_driver_info;
extern struct sr_dev_driver microchip_pickit2_driver_info;
extern struct sr_dev_driver motech_lps_301_driver_info;
extern struct sr_dev_driver norma_dmm_driver_info;
extern struct sr_dev_driver siemens_b102x_driver_info;
extern struct sr_dev_driver ols_driver_info;
extern struct sr_dev_driver pce_322a_driver_info;
extern struct sr_dev_driver p_ols_driver_info;
extern struct sr_dev_driver raspberrypi_pico_driver_info;
extern struct sr_dev_driver rdtech_dps_driver_info;
extern struct sr_dev_driver rdtech_rd_driver_info;
extern struct sr_dev_driver rdtech_tc_driver_info;
extern struct sr_dev_driver rdtech_um_driver_info;
extern struct sr_dev_driver rigol_dg_driver_info;
extern struct sr_dev_driver rigol_ds_driver_info;
extern struct sr_dev_driver rohde_schwarz_sme_0x_driver_info;
extern struct sr_dev_driver saleae_logic_pro_driver_info;
extern struct sr_dev_driver saleae_logic16_driver_info;
extern struct sr_dev_driver scpi_dmm_driver_info;
extern struct sr_dev_driver scpi_pps_driver_info;
extern struct sr_dev_driver hp_ib_pps_driver_info;
extern struct sr_dev_driver siglent_sdl10x0_driver_info;
extern struct sr_dev_driver siglent_sds_driver_info;
extern struct sr_dev_driver sysclk_lwla_driver_info;
extern struct sr_dev_driver sysclk_sla5032_driver_info;
extern struct sr_dev_driver teleinfo_driver_info;
extern struct sr_dev_driver testo_driver_info;
extern struct sr_dev_driver tondaj_sl_814_driver_info;
extern struct sr_dev_driver uni_t_ut181a_driver_info;
extern struct sr_dev_driver uni_t_ut32x_driver_info;
extern struct sr_dev_driver yokogawa_dlm_driver_info;
extern struct sr_dev_driver zeroplus_logic_cube_driver_info;
extern struct sr_dev_driver zketech_ebd_usb_driver_info;
/* sipeed-slogic-analyzer was excluded from the migration script (already
 * migrated manually beforehand) — added here so batch registration covers it. */
extern struct sr_dev_driver sipeed_slogic_analyzer_driver_info;

/* TODO: The following drivers use SR_REGISTER_DEV_DRIVER_LIST multi-driver
 * mode and are not yet migrated: kern-scale, serial-dmm, serial-lcr,
 * uni-t-dmm. These need manual migration to expose their driver arrays. */

/* Returns NULL-terminated array of all migrated driver_info pointers. */
struct sr_dev_driver **srstd_get_all_drivers(void)
{
    static struct sr_dev_driver *drivers[] = {
        &agdmm_driver_info,
        &appa_55ii_driver_info,
        &arachnid_labs_re_load_pro_driver_info,
        &asix_omega_rtm_cli_driver_info,
        &asix_sigma_driver_info,
        &atorch_driver_info,
        &atten_pps3203_driver_info,
        &bkprecision_1856d_driver_info,
        &cem_dt_885x_driver_info,
        &center_309_driver_info,
        &voltcraft_k204_driver_info,
        &chronovu_la_driver_info,
        &colead_slm_driver_info,
        &conrad_digi_35_cpu_driver_info,
        &devantech_eth008_driver_info,
        &fluke_45_driver_info,
        &flukedmm_driver_info,
        &ftdi_la_driver_info,
        &fx2lafw_driver_info,
        &gmc_mh_1x_2x_rs232_driver_info,
        &gmc_mh_2x_bd232_driver_info,
        &greatfet_driver_info,
        &gwinstek_gds_800_driver_info,
        &gwinstek_gpd_driver_info,
        &gwinstek_psp_driver_info,
        &hameg_hmo_driver_info,
        &hantek_4032l_driver_info,
        &hantek_6xxx_driver_info,
        &hantek_dso_driver_info,
        &hp_3457a_driver_info,
        &hp_3478a_driver_info,
        &hp_59306a_driver_info,
        &icstation_usbrelay_driver_info,
        &ikalogic_scanalogic2_driver_info,
        &ikalogic_scanaplus_driver_info,
        &ipdbg_la_driver_info,
        &itech_it8500_driver_info,
        &juntek_jds6600_driver_info,
        &kecheng_kc_330b_driver_info,
        &kingst_la2016_driver_info,
        &korad_kaxxxxp_driver_info,
        &lascar_el_usb_driver_info,
        &lecroy_logicstudio_driver_info,
        &lecroy_xstream_driver_info,
        &manson_hcs_3xxx_driver_info,
        &mastech_ms6514_driver_info,
        &maynuo_m97_driver_info,
        &mic_98581_driver_info,
        &mic_98583_driver_info,
        &microchip_pickit2_driver_info,
        &motech_lps_301_driver_info,
        &norma_dmm_driver_info,
        &siemens_b102x_driver_info,
        &ols_driver_info,
        &pce_322a_driver_info,
        &p_ols_driver_info,
        &raspberrypi_pico_driver_info,
        &rdtech_dps_driver_info,
        &rdtech_rd_driver_info,
        &rdtech_tc_driver_info,
        &rdtech_um_driver_info,
        &rigol_dg_driver_info,
        &rigol_ds_driver_info,
        &rohde_schwarz_sme_0x_driver_info,
        &saleae_logic_pro_driver_info,
        &saleae_logic16_driver_info,
        &scpi_dmm_driver_info,
        &scpi_pps_driver_info,
        &hp_ib_pps_driver_info,
        &siglent_sdl10x0_driver_info,
        &siglent_sds_driver_info,
        &sysclk_lwla_driver_info,
        &sysclk_sla5032_driver_info,
        &teleinfo_driver_info,
        &testo_driver_info,
        &tondaj_sl_814_driver_info,
        &uni_t_ut181a_driver_info,
        &uni_t_ut32x_driver_info,
        &yokogawa_dlm_driver_info,
        &zeroplus_logic_cube_driver_info,
        &zketech_ebd_usb_driver_info,
        &sipeed_slogic_analyzer_driver_info,
        NULL
    };
    return drivers;
}
